# Generated by Django 4.0.3 on 2022-10-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gwangjingu',
            new_name='Seoul',
        ),
        migrations.DeleteModel(
            name='Dobonggu',
        ),
        migrations.DeleteModel(
            name='Dongdaemungu',
        ),
        migrations.DeleteModel(
            name='Dongjakgu',
        ),
        migrations.DeleteModel(
            name='Eunpyeonggu',
        ),
        migrations.DeleteModel(
            name='Gangbukgu',
        ),
        migrations.DeleteModel(
            name='Gangdonggu',
        ),
        migrations.DeleteModel(
            name='Gangnamgu',
        ),
        migrations.DeleteModel(
            name='Gangseogu',
        ),
        migrations.DeleteModel(
            name='Geumcheongu',
        ),
        migrations.DeleteModel(
            name='Gurogu',
        ),
        migrations.DeleteModel(
            name='Gwanakgu',
        ),
        migrations.DeleteModel(
            name='Jongnogu',
        ),
        migrations.DeleteModel(
            name='Junggu',
        ),
        migrations.DeleteModel(
            name='Jungnanggu',
        ),
        migrations.DeleteModel(
            name='Mapogu',
        ),
        migrations.DeleteModel(
            name='Nowongu',
        ),
        migrations.DeleteModel(
            name='Seochogu',
        ),
        migrations.DeleteModel(
            name='Seodaemungu',
        ),
        migrations.DeleteModel(
            name='Seongbukgu',
        ),
        migrations.DeleteModel(
            name='Seongdonggu',
        ),
        migrations.DeleteModel(
            name='Songpagu',
        ),
        migrations.DeleteModel(
            name='Yangcheongu',
        ),
        migrations.DeleteModel(
            name='Yeongdeungpogu',
        ),
        migrations.DeleteModel(
            name='Yongsangu',
        ),
    ]
